Name:           ros-indigo-motoman
Version:        0.3.7
Release:        0%{?dist}
Summary:        ROS motoman package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/motoman
Source0:        %{name}-%{version}.tar.gz

BuildArch:      noarch

Requires:       ros-indigo-motoman-driver
Requires:       ros-indigo-motoman-mh5-support
Requires:       ros-indigo-motoman-sia10d-support
Requires:       ros-indigo-motoman-sia20d-moveit-config
Requires:       ros-indigo-motoman-sia20d-support
Requires:       ros-indigo-motoman-sia5d-support
BuildRequires:  ros-indigo-catkin

%description
The motoman stack constains libraries, configuration files, and ROS nodes for
controlling a Motoman robot from ROS-Industrial

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Tue Mar 21 2017 Shaun Edwards <sedwards@swri.org> - 0.3.7-0
- Autogenerated by Bloom

* Mon Mar 20 2017 Shaun Edwards <sedwards@swri.org> - 0.3.6-0
- Autogenerated by Bloom

* Sun Jul 03 2016 Shaun Edwards <sedwards@swri.org> - 0.3.5-0
- Autogenerated by Bloom

